name: GitHub-Profile-3D-Contrib-gpt

on:
  schedule: # 매일 18:00 UTC (03:00 JST)
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "bonun00"
          git config user.email "lifesciences00@naver.com"
          git pull origin main --rebase
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          git push
